"""create booking_requests table

Revision ID: 4c782c7d30af
Revises: 
Create Date: 2026-04-15 13:55:58.887481

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4c782c7d30af'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('booking_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slot_id', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=30), nullable=False),
    sa.Column('subject_summary', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=30), server_default='received', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_booking_requests_email'), 'booking_requests', ['email'], unique=False)
    op.create_index(op.f('ix_booking_requests_slot_id'), 'booking_requests', ['slot_id'], unique=False)
    op.create_index(op.f('ix_booking_requests_status'), 'booking_requests', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_booking_requests_status'), table_name='booking_requests')
    op.drop_index(op.f('ix_booking_requests_slot_id'), table_name='booking_requests')
    op.drop_index(op.f('ix_booking_requests_email'), table_name='booking_requests')
    op.drop_table('booking_requests')
    # ### end Alembic commands ###
